-- verdant M01-PR03 migration 0001_init (RESERVED prefix 0001).
--
-- Compact change record (integration §2; the same record is mirrored as
-- `storage::MIGRATION_0001` so tests assert record and file agree):
--   backend + owner .....: sqlite / M01-PR03 (durable stores + transactions)
--   predecessors ........: none (initial schema; no other migration IDs exist)
--   fresh-install .......: apply this file, then `PRAGMA user_version = 1`
--   supported upgrade ...: none yet; the first future migration MUST be 0002
--                          with predecessor 0001 and an explicit backfill plan
--   queued-msg compat ...: outbox rows are additive; small duplicate rows under
--                          concurrent writers are TOLERATED and counted, never
--                          silently merged (binding rules arrive PR07 earliest)
--   lock / space needs ..: WAL mode; one writer at a time (SQLite file locks +
--                          5 s busy timeout); WAL size capped by journal_size_limit
--                          (see StoreBounds); temp DBs live in OS temp dirs only
--   interruption outcome : uncommitted work never survives (connection close or
--                          process kill rolls back to the last commit);
--                          claimed-but-unacked rows stay visibly dangling across
--                          restart and are NEVER silently requeued or dropped
--   read / write policy .: every connection sets + verifies WAL + FULL-sync +
--                          foreign-keys + busy-timeout per connection (recorded,
--                          never inferred); SQLite `synchronous=FULL` returns
--                          after the OS acknowledges the write (process-crash
--                          evidence only — NOT a power-loss proof)
--   rollback boundary ...: applied migrations are never rewritten (AGENTS.md);
--                          data rollback is explicit per-row (requeue/ack), not
--                          a schema downgrade; there is no `down` migration
--
-- Applied migrations are never rewritten. Do NOT edit this file after merge;
-- change arrives as a new numbered migration owned by the integration owner.

CREATE TABLE IF NOT EXISTS schema_migrations (
    generation INTEGER PRIMARY KEY,
    applied_note TEXT NOT NULL
);

-- Tiny outbox: one row per queued operation. `status` is the claim lifecycle
-- (queued -> claimed -> acked). `claimed_by` is the handoff token that owns a
-- claim; a NULL token means never claimed. `generation` + `seq` carry the
-- domain RecordIdentity so restored counters cannot silently alias records.
CREATE TABLE IF NOT EXISTS outbox (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    operation TEXT NOT NULL,
    entity TEXT NOT NULL,
    sensor TEXT NOT NULL,
    value_json TEXT NOT NULL,
    unit TEXT NOT NULL,
    source_ms TEXT NOT NULL,
    receipt_ms TEXT NOT NULL,
    ingestion_ms TEXT NOT NULL,
    generation TEXT NOT NULL,
    seq TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'queued'
        CHECK (status IN ('queued', 'claimed', 'acked')),
    claimed_by TEXT,
    created_nanos TEXT NOT NULL DEFAULT '0'
);

CREATE INDEX IF NOT EXISTS idx_outbox_status ON outbox (status);

-- Derived-state dirtiness: inserting outbox rows marks the entity dirty (1).
-- Only an explicit checked recalculation for the CURRENT schema generation
-- clears the flag. Restart preserves dirty flags; checkpointing never clears
-- them (a checkpoint protects checkpointed bytes, not derived correctness).
CREATE TABLE IF NOT EXISTS derived_marks (
    entity TEXT PRIMARY KEY,
    dirty INTEGER NOT NULL DEFAULT 1 CHECK (dirty IN (0, 1)),
    checked_generation INTEGER NOT NULL DEFAULT 0
);
