//! E03 test-only loopback TCP peer. Real pinned TcpTransport + ModbusClient;
//! capture client framed boundaries and independently scripted peer socket bytes.
//! No simulator/server dependency, raw socket framing in product, or pcap claim.
use super::*;
use crate::runtime::{
    bacnet::test_loopback::{PacketLog, PORT_RELEASE_GUARD},
    Runtime,
};
use rusty_modbus_frame::{Frame, FrameHeader};
use rusty_modbus_tcp::{TcpRecvStream, TransportError};
use std::net::{Ipv4Addr, SocketAddr};
use tokio::{
    io::{AsyncReadExt, AsyncWriteExt},
    net::TcpSocket,
    sync::oneshot,
    task::JoinHandle,
};

pub(crate) struct Step {
    /// FULL independently specified MBAP+PDU, never generated by the encoder.
    pub request: Vec<u8>,
    pub response: Option<Vec<u8>>,
}
fn wire(frame: &Frame) -> Vec<u8> {
    let FrameHeader::Mbap(header) = frame.header else {
        panic!("TCP only")
    };
    let mut bytes = Vec::new();
    bytes.extend(header.transaction_id.get().to_be_bytes());
    bytes.extend(header.protocol_id.get().to_be_bytes());
    bytes.extend(header.length.get().to_be_bytes());
    bytes.push(header.unit_id);
    bytes.extend_from_slice(&frame.pdu);
    assert_mbap(&bytes);
    bytes
}
fn assert_mbap(bytes: &[u8]) {
    assert!((8..=260).contains(&bytes.len()));
    assert_eq!(&bytes[2..4], &[0, 0]);
    assert_eq!(
        usize::from(u16::from_be_bytes([bytes[4], bytes[5]])) + 6,
        bytes.len()
    );
}
pub(crate) struct CapturedSink {
    inner: TcpSink,
    log: PacketLog,
    local: SocketAddr,
    peer: SocketAddr,
}
impl TransportSink for CapturedSink {
    async fn send(&mut self, frame: Frame) -> std::result::Result<(), TransportError> {
        let bytes = wire(&frame);
        assert!(matches!(bytes[7], 1..=4), "forbidden request function");
        assert!(matches!(bytes[6], 1..=247 | 255), "broadcast/reserved unit");
        self.inner.send(frame).await?;
        self.log.record(true, self.local, self.peer, &bytes);
        Ok(())
    }
}
struct CapturedStream {
    inner: TcpRecvStream,
    log: PacketLog,
    local: SocketAddr,
    peer: SocketAddr,
}
impl TransportStream for CapturedStream {
    async fn recv(&mut self) -> std::result::Result<Frame, TransportError> {
        let frame = self.inner.recv().await?;
        self.log.record(false, self.peer, self.local, &wire(&frame));
        Ok(frame)
    }
}
pub(crate) struct Pair {
    _ports: tokio::sync::MutexGuard<'static, ()>,
    pub client: SocketAddr,
    pub peer: SocketAddr,
    pub log: PacketLog,
    close: Option<oneshot::Sender<()>>,
    half_closed: Option<oneshot::Receiver<()>>,
    task: Option<JoinHandle<()>>,
}
impl Pair {
    pub async fn new(
        runtime: &mut Runtime,
        map: impl FnOnce(Target) -> Map,
        unit: u8,
        steps: Vec<Step>,
        timeout: Duration,
    ) -> (Self, Client<CapturedSink>) {
        Self::at(runtime, map, unit, steps, timeout, None).await
    }
    pub async fn reconnect(
        runtime: &mut Runtime,
        previous: &Client<CapturedSink>,
        steps: Vec<Step>,
    ) -> (Self, Client<CapturedSink>) {
        let map = previous.map.clone();
        let coverage = previous.reconnect_coverage(&map).unwrap();
        let target = map.target();
        let (pair, mut client) = Self::at(
            runtime,
            |_| map,
            target.unit(),
            steps,
            TIMEOUT,
            Some(target.address()),
        )
        .await;
        client.coverage = coverage;
        (pair, client)
    }
    async fn at(
        runtime: &mut Runtime,
        map: impl FnOnce(Target) -> Map,
        unit: u8,
        steps: Vec<Step>,
        timeout: Duration,
        address: Option<SocketAddr>,
    ) -> (Self, Client<CapturedSink>) {
        assert!(!steps.is_empty() && steps.len() <= admission::MAX_SCRIPTS);
        for step in &steps {
            assert_eq!(step.request.len(), 12);
            assert_mbap(&step.request);
            if let Some(response) = &step.response {
                assert_mbap(response);
            }
        }
        assert!(!timeout.is_zero() && timeout <= TIMEOUT);
        let ports = PORT_RELEASE_GUARD.lock().await;
        let socket = TcpSocket::new_v4().unwrap();
        socket.set_reuseaddr(true).unwrap();
        socket
            .bind(address.unwrap_or_else(|| (Ipv4Addr::LOCALHOST, 0).into()))
            .unwrap();
        let listener = socket.listen(1).unwrap();
        let peer = listener.local_addr().unwrap();
        let permit = runtime
            .fixture_modbus(map(Target::loopback(peer, unit).unwrap()))
            .unwrap();
        // Same public transport/configuration as Client::connect. The decorator
        // changes only test capture; it does not implement a replacement codec.
        let tcp = TcpConfig {
            connect_timeout: timeout,
            read_timeout: Some(timeout),
            write_timeout: Some(timeout),
            ..TcpConfig::default()
        };
        let (sink, stream) = TcpTransport::connect(tcp, peer).await.unwrap();
        let (mut socket, client) = listener.accept().await.unwrap();
        let log = PacketLog::default();
        let task_log = log.clone();
        let (close, stop) = oneshot::channel();
        let (half_close, half_closed) = oneshot::channel();
        let task = tokio::spawn(async move {
            let _listener = listener;
            for step in steps {
                let mut received = [0; 12];
                tokio::time::timeout(Duration::from_secs(5), socket.read_exact(&mut received))
                    .await
                    .unwrap()
                    .unwrap();
                task_log.record(false, client, peer, &received);
                assert_eq!(
                    received.as_slice(),
                    step.request,
                    "independent MBAP transaction/unit/length/address/quantity"
                );
                if let Some(response) = step.response {
                    // Deliberate stream fragmentation across MBAP header/PDU.
                    socket.write_all(&response[..5]).await.unwrap();
                    socket.write_all(&response[5..]).await.unwrap();
                    task_log.record(true, peer, client, &response);
                }
            }
            stop.await.unwrap();
            socket.shutdown().await.unwrap(); // peer FIN first: avoid client TIME_WAIT
            half_close.send(()).unwrap();
            let mut extra = [0; 260];
            let n = tokio::time::timeout(Duration::from_secs(5), socket.read(&mut extra))
                .await
                .unwrap()
                .unwrap();
            assert_eq!(
                n, 0,
                "unexpected retry/write/routing request or retained client socket"
            );
        });
        let wrapper = Client::from_transport(
            permit,
            CapturedSink {
                inner: sink,
                log: log.clone(),
                local: client,
                peer,
            },
            CapturedStream {
                inner: stream,
                log: log.clone(),
                local: client,
                peer,
            },
            timeout,
        )
        .unwrap();
        (
            Self {
                _ports: ports,
                client,
                peer,
                log,
                close: Some(close),
                half_closed: Some(half_closed),
                task: Some(task),
            },
            wrapper,
        )
    }
    pub async fn half_close(&mut self) {
        if let Some(close) = self.close.take() {
            close.send(()).unwrap();
        }
        if let Some(closed) = self.half_closed.take() {
            closed.await.unwrap();
        }
    }
    pub async fn finish(mut self, case: &str, client: &mut Client<CapturedSink>) {
        self.half_close().await;
        client.shutdown().await.unwrap();
        assert!(!client.is_connected());
        client.shutdown().await.unwrap(); // idempotent, already physically dropped
        if let Some(task) = self.task.as_mut() {
            task.await.unwrap();
        }
        self.task = None;
        self.log.assert_tcp_complete(self.client, self.peer);
        assert!(self.log.packets().len() <= 32, "declared capture payload bound");
        let a = released(self.client).await;
        let b = released(self.peer).await;
        let sent: usize = self
            .log
            .packets()
            .iter()
            .filter(|p| p.sent)
            .map(|p| p.bytes.len())
            .sum();
        eprintln!("MODBUS-CAPTURE {case} client={} peer={} records={} sent=received={sent} MBAP/exact/direct/127.0.0.1/no-502-802=PASS shutdown/join/EOF/rebind-both=PASS (fixture boundaries, not pcap)", self.client, self.peer, self.log.packets().len());
        drop((a, b));
    }
}
impl Drop for Pair {
    fn drop(&mut self) {
        if let Some(task) = &self.task {
            task.abort();
        }
        // Panic/cancellation cleanup only, never a passing capture/join report.
    }
}
async fn released(address: SocketAddr) -> TcpSocket {
    let deadline = Instant::now() + Duration::from_secs(5);
    loop {
        let socket = TcpSocket::new_v4().unwrap();
        socket.set_reuseaddr(true).unwrap();
        match socket.bind(address) {
            Ok(()) => return socket,
            Err(e) if e.kind() == std::io::ErrorKind::AddrInUse && Instant::now() < deadline => {
                tokio::time::sleep(Duration::from_millis(1)).await
            }
            Err(e) => panic!("TCP rebind {address} not observed: {e}"),
        }
    }
}
